title: StudyMore - Par le Lycée George Sand
email: thisiskeanyvy@tuta.io #Contact Keany Vy KHUN (pro)
description: >- # this means to ignore newlines until "baseurl:"
  Lycée George Sand - Enseignants, élèves et parents. Grâce à StudyMore, vos cours et documents sont consultables en quelques clics.

# uncomment for github pages utilisation
baseurl: # the subpath of your site, e.g. /blog
url: https://lyc-sand.github.io # the base hostname & protocol for your site, e.g. http://example.com
# uncomment for local utilisation and build
#baseurl:
#url:
twitter_username: LyceeSandDomont
github_username:  lyc-sand
instagram_username: lyc_georgesand

markdown: kramdown
permalink: /:categories/:title
collections:
  - seconde

collections_dir: cours
collections:
  seconde:
    output: true
    permalink: /classe_seconde/:categories/:name
    order:
      - allemand/*.md
      - anglais/*.md
      - enseignement moral et civique/*.md
      - espagnol/*.md
      - français/*.md
      - histoire-géographie/*.md
      - mathématiques/*.md
      - physique-chimie/*.md
      - sciences de la vie et de la terre/*.md
      - sciences économiques et sociales/*.md
      - sciences numériques et technologie/*.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
